export const DATE_FORMATS = {
  FULL_YEAR: /YYYY/,
  SHORT_YEAR: /YY/,
  FULL_MONTH: /MM/,
  SHORT_MONTH: /M/,
  FULL_DAY: /DD/,
  SHORT_DAY: /D/,
  FULL_HOUR: /HH/,
  SHORT_HOUR: /H/,
  FULL_MINUTES: /mm/,
  SHORT_MINUTES: /m/,
  FULL_SECONDS: /ss/,
  SHORT_SECONDS: /s/,
}